'use strict';

const fs = require('node:fs');
const path = require('node:path');
const logger = require('./logger');

const readFileSync = (filePath, errorContext = '') => {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch (error) {
    const context = errorContext ? ` ${errorContext}` : '';
    logger.error(`Failed to read file${context}: ${filePath}`);
    logger.error(error.message);
    return process.exit(1);
  }
};

const writeFileSync = (filePath, content, errorContext = '') => {
  try {
    return fs.writeFileSync(filePath, content, 'utf8');
  } catch (error) {
    const context = errorContext ? ` ${errorContext}` : '';
    logger.error(`Failed to write file${context}: ${filePath}`);
    logger.error(error.message);
    return process.exit(1);
  }
};

const readJsonSync = (filePath, errorContext = '') => {
  const content = readFileSync(filePath, errorContext);
  try {
    return JSON.parse(content);
  } catch (error) {
    const context = errorContext ? ` ${errorContext}` : '';
    logger.error(`Failed to parse JSON${context}: ${filePath}`);
    logger.error(error.message);
    return process.exit(1);
  }
};

const fileExists = (filePath) => {
  try {
    fs.accessSync(filePath, fs.constants.F_OK);
    return true;
  } catch {
    return false;
  }
};

const ensureDirectory = (dirPath) => {
  if (!fs.existsSync(dirPath)) {
    try {
      fs.mkdirSync(dirPath, { recursive: true });
    } catch (error) {
      logger.error(`Failed to create directory: ${dirPath}`);
      logger.error(error.message);
      process.exit(1);
    }
  }
};

const resolveFilePath = (basePath, ...segments) =>
  path.join(basePath, ...segments);

const BUNDLE_EXT = {
  lib: '.mjs',
  iife: '.iife.js',
  symlinked: '.js',
};
const GENERATED_BY = `// Generated by metarhia-build. Don't edit this file.\n`;

module.exports = {
  readFileSync,
  writeFileSync,
  readJsonSync,
  fileExists,
  ensureDirectory,
  resolveFilePath,
  BUNDLE_EXT,
  GENERATED_BY,
};
